In [17]:
import pandas as pd
import numpy as np

In [29]:
i = 0
df=pd.read_table('/home/groups/dpwall/briannac/alt_haplotypes/intermediate_files/kmers/kmers.%i.tsv.gz' % i)

In [40]:
df = df[df.sum(axis=1)>0]
df

,02C11611,03C16111,03C16611,03C17011,03C17211,03C19911,03C23211,04C26311,04C27811,04C29411,...,04C37711,05C44411,05C45011,05C50311,06C59211,07C68911,09C97611,10C111411,10C111711,10C114411
0,14268,8660,23588,57220,79284,18582,18530,65976,17882,39455,...,106481,24974,25340,21025,70518,11151,33665,32336,79993,56873
21,0,5,0,0,0,0,5,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,4,0,0
35,0,0,0,0,0,0,0,6,0,4,...,5,3,0,0,0,0,0,0,0,0
41,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
951,0,0,0,0,0,0,0,0,0,0,...,0,0,2,3,5,0,0,0,0,0
969,0,0,0,0,0,0,0,0,0,0,...,0,0,2,0,0,0,0,0,0,0
987,0,0,0,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
990,0,0,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
992,0,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [42]:
df.iloc[np.argsort(df.sum(axis=1))[::-1].values][::10]

,02C11611,03C16111,03C16611,03C17011,03C17211,03C19911,03C23211,04C26311,04C27811,04C29411,...,04C37711,05C44411,05C45011,05C50311,06C59211,07C68911,09C97611,10C111411,10C111711,10C114411
0,14268,8660,23588,57220,79284,18582,18530,65976,17882,39455,...,106481,24974,25340,21025,70518,11151,33665,32336,79993,56873
268,2,5,0,3,2,0,4,3,2,4,...,4,4,4,5,0,2,5,2,0,7
645,4,0,0,0,4,0,0,5,0,0,...,0,5,0,0,0,0,0,2,0,0
516,0,0,0,0,10,0,0,0,0,0,...,0,0,0,0,0,0,0,2,0,0
585,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,9,0,0,0
447,0,0,0,0,0,0,0,0,0,0,...,0,0,0,3,0,0,0,2,0,0
318,0,0,0,0,0,0,3,0,0,0,...,0,0,0,0,0,0,0,0,0,0
237,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,0,0
931,0,0,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
703,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0
595,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0